export const API: string  = 'http://localhost:8080'
export const apiRegister:string  = 'http://localhost:8080/auth/register'
export const apiLogin: string = 'http://localhost:8080/auth/login'
export const  apiToken:string='http://localhost:8080/token'
export const apiFacturation: string = 'http://localhost:8080/payement/standard'